### ISSUE TITLE
Increase set limit per exercise from 12

### ISSUE THREAD

**Issue by craigloewen-msft** [Weightlifting-App/WeightliftingApp-Support#1]
I'm doing an [Escalation Density Training](https://revolutionaryprogramdesign.com/density/) routine, and it involves going up to as many as 20 or 30 sets per single exercise in one workout. 

Right now the set limit per exercise is 12, which makes it hard for me to track my total volume (I have to split it out into two repeated exercises usually).

Could you increase the set limit to something like 50 instead? 

Thank you! (And love the app!)

**Comment by chappyasel** [comment]
Hi Craig - thank you for the feedback and kind words! 

We are increasing the limit to 30 sets in version 5.7. Enjoy!
